### ISSUE TITLE
kmod intel  iommu ?

### ISSUE THREAD

**Issue by MaurUppi** [k13132/openwrt-dpdk#1]
1. 可否增加intel  iommu MAKEFILE 呢？我不知道怎么改你现有的AMD iommu MAKEFILE
2. kmod-vfio-pci、 kmod-uio_pci_generic有了，貌似不需要考虑HUGETLB？

https://doc.dpdk.org/guides/howto/openwrt.html
12.2.2. Kernel configuration
The following configurations should be enabled:

```
CONFIG_VFIO_IOMMU_TYPE1=y
CONFIG_VFIO_VIRQFD=y
CONFIG_VFIO=y
CONFIG_VFIO_NOIOMMU=y
CONFIG_VFIO_PCI=y
CONFIG_VFIO_PCI_MMAP=y
CONFIG_HUGETLBFS=y
CONFIG_HUGETLB_PAGE=y
CONFIG_PROC_PAGE_MONITOR=y
```

**Comment by zokl** [comment]
Hello, all of you mentioned modules are in my repository packages.
