### ISSUE TITLE
cross-compile for arm status 2024

### ISSUE THREAD

**Issue by BlueWaterCrystal** [k13132/openwrt-dpdk#16]
Hi,

Has this code been tested on arm?

I'm trying to cross-compile for MT7986(Filogic 830). 

The master returns this: 
`Problem encountered: Arm SoC must be specified in the cross file.`

Devel returns this:
`toolchain-aarch64_cortex-a53_gcc-13.2.0_musl/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp]
    1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
      |  ^~~~~~~
shm.c: In function 'attach_shared':
shm.c:138:23: error: storage size of 'st' isn't known
  138 |         struct stat64 st;
      |                       ^~
shm.c:149:13: warning: implicit declaration of function 'fstat64'; did you mean 'fstatat'? [-Wimplicit-function-declaration]
  149 |         if (fstat64(shmfd, &st) < 0)
      |             ^~~~~~~
      |             fstatat
shm.c:156:21: warning: implicit declaration of function 'ftruncate64'; did you mean 'ftruncate'? [-Wimplicit-function-declaration]
  156 |                 if (ftruncate64(shmfd, shmlen + shmoffset) < 0) {
      |                     ^~~~~~~~~~~
      |                     ftruncate
shm.c:171:18: warning: implicit declaration of function 'mmap64'; did you mean 'mmap'? [-Wimplicit-function-declaration]
  171 |         shmptr = mmap64(NULL, shmlen, PROT_READ | PROT_WRITE, MAP_SHARED, shmfd, shmoffset);
      |                  ^~~~~~
      |                  mmap
shm.c:171:16: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  171 |         shmptr = mmap64(NULL, shmlen, PROT_READ | PROT_WRITE, MAP_SHARED, shmfd, shmoffset);
      |                ^
shm.c:138:23: warning: unused variable 'st' [-Wunused-variable]
  138 |         struct stat64 st;`

**Comment by zokl** [comment]
Hi this code is not supported by arm now. I will push working code in few days.

**Comment by zokl** [comment]
Hello, try this branch https://github.com/k13132/openwrt-dpdk/tree/arm

**Comment by BlueWaterCrystal** [comment]
> Hello, try this branch https://github.com/k13132/openwrt-dpdk/tree/arm

Hi, the link returns 404 - page not found

I presume it's been merged with main?

**Comment by zokl** [comment]
> > Hello, try this branch https://github.com/k13132/openwrt-dpdk/tree/arm
> 
> Hi, the link returns 404 - page not found

Sorry, I moved i to master https://github.com/k13132/openwrt-dpdk

**Comment by akanouras** [comment]
@BlueWaterCrystal do you have a DPDK NIC driver for the MT7986?
