### ISSUE TITLE
Can you add support for the R8125 Ethernet driver?

### ISSUE THREAD

**Issue by smdx** [k13132/openwrt-dpdk#18]
Hello, can you add support for R8125 Ethernet driver? Thank you

**Comment by zokl** [comment]
Hi. 

The current version of dpdk integration for OpenWRT is based on DPDK 24.03, and this version of dpdk does not have R8125 drivers.  Maybe the new release of DPDK includes this driver - http://patches.dpdk.org/project/dpdk/patch/20240527061528.10072-1-howard_wang@realsil.com.cn/. If you want, you can make PR for these changes ...
