### ISSUE TITLE
cross compile for arm64 failed

### ISSUE THREAD

**Issue by youkechat** [k13132/openwrt-dpdk#3]
error log
../../build_dir/target-aarch64_generic_musl/dpdk-22.03/config/arm/meson.build:484:12: ERROR: Problem encountered: Arm SoC must be specified in the cross file.

need change MESON_CPU value Makefile? my cpu is RK3399, use this value failed, What value shoud I use?

**Comment by youkechat** [comment]
fixed by change openwrt-cross.txt.in by add platform

**Comment by zokl** [comment]
Please send me a longer output from your compilation log. I would like to check if for Makefile correction.
