### ISSUE TITLE
Cross-compilation for DPDK with ARM-based OpenWrt 

### ISSUE THREAD

**Issue by ghost-script** [k13132/openwrt-dpdk#4]
This repository is prepared for DPDK and OpenWrt in x86_64-based environment. I am building OpenWrt for the ARM target on a x86_64 machine using Ubuntu, and I am currently using the build on a ARM-based device but I would like to enable DPDK on it. Do you plan to provide ARM option? If the answer is no, do you have any suggestions about the required modifications to this repository?

**Comment by zokl** [comment]
> This repository is prepared for DPDK and OpenWrt in x86_64-based environment. I am building OpenWrt for the ARM target on a x86_64 machine using Ubuntu, and I am currently using the build on a ARM-based device but I would like to enable DPDK on it. Do you plan to provide ARM option? If the answer is no, do you have any suggestions about the required modifications to this repository?

Hello, I would like to prepare an ARM modification but not now maybe in several months. You can help me :-).

**Comment by zokl** [comment]
For ARM please use the package as usual and send me the compilation errors that you will have.

**Comment by zokl** [comment]
Hello @ghost-script, is it possible to test build dpdk on ARM with the packages from devel branch? We switch to MUSL compiler.

**Comment by zokl** [comment]
Resolved in https://github.com/k13132/openwrt-dpdk/tree/arm
