### ISSUE TITLE
missing dependencies for the following libraries: libbsd.so.0

### ISSUE THREAD

**Issue by stevenke1981** [k13132/openwrt-dpdk#6]
touch /home/steven/openwrt/staging_dir/target-x86_64_glibc/root-x86/stamp/.libdpdk_installed
mkdir -p /home/steven/openwrt/bin/targets/x86/64-glibc/packages /home/steven/openwrt/build_dir/target-x86_64_glibc/dpdk-22.07/ipkg-x86_64/libdpdk/CONTROL /home/steven/openwrt/staging_dir/target-x86_64_glibc/pkginfo
install -d -m0755 /home/steven/openwrt/build_dir/target-x86_64_glibc/dpdk-22.07/ipkg-x86_64/libdpdk/usr/lib
install -m0755 /home/steven/openwrt/build_dir/target-x86_64_glibc/dpdk-22.07/ipkg-install/usr/lib/librte_*.so.* /home/steven/openwrt/build_dir/target-x86_64_glibc/dpdk-22.07/ipkg-x86_64/libdpdk/usr/lib/
find /home/steven/openwrt/build_dir/target-x86_64_glibc/dpdk-22.07/ipkg-x86_64/libdpdk -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package libdpdk is missing dependencies for the following libraries:
libbsd.so.0
make[2]: *** [Makefile:104: /home/steven/openwrt/bin/packages/x86_64/dpdk_repo/libdpdk_22.07-1_x86_64.ipk] Error 1

**Comment by zokl** [comment]
Hi, which version of OpenWRT and platform do you have?

**Comment by stevenke1981** [comment]
Openwrt 22.03.3
VM machine :ubuntu 18.05
I followed this
https://forum.openwrt.org/t/compiling-openwrt-to-support-dpdk/151982

And add this repo

**Comment by stevenke1981** [comment]
Oh,oops maybe I make a mistake on the DPDK version,I will try it later, thank you

**Comment by zokl** [comment]
Fixed in https://github.com/k13132/openwrt-dpdk/commit/0abe11d724cf74a3be22f850e22360fed48c29c2
